# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres       # Substitua pelo seu usuário do PostgreSQL (default: postgres)
  password: admin          # Substitua pela sua senha do PostgreSQL (default: admin)
  host: localhost

development:
  <<: *default
  database: todo_app_development # Banco de dados para desenvolvimento

test:
  <<: *default
  database: todo_app_test        # Banco de dados para testes automatizados

production:
  <<: *default
  database: todo_app_production  # Banco de dados para produção
  username: postgres             # Usuário para o ambiente de produção
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %> # Senha para produção, recomendada via variável de ambiente